# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='fieldtype',
        ),
        migrations.AddField(
            model_name='field',
            name='ftype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.FieldType'),
            preserve_default=False,
        ),
    ]
