# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foo',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='foo',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
