# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170120_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='fooattribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Attribute')),
                ('foo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Foo')),
            ],
        ),
        migrations.AddField(
            model_name='foo',
            name='attribute',
            field=models.ManyToManyField(through='core.fooattribute', to='core.Attribute'),
        ),
    ]
