# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170120_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500)),
                ('foo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Foo')),
            ],
        ),
    ]
