# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fooanswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
