# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20170120_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Node')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.NodeNote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Node')),
            ],
        ),
        migrations.RenameModel(
            old_name='FieldType',
            new_name='EType',
        ),
        migrations.RenameModel(
            old_name='profilefieldview',
            new_name='ProfileExpander',
        ),
        migrations.RenameModel(
            old_name='Attribute',
            new_name='Trait',
        ),
        migrations.RemoveField(
            model_name='field',
            name='ftype',
        ),
        migrations.RemoveField(
            model_name='field',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='foo',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fooanswer',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='fooanswer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='fooanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fooattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='fooattribute',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='profileexpander',
            name='field',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.DeleteModel(
            name='FooAnswer',
        ),
        migrations.DeleteModel(
            name='fooattribute',
        ),
        migrations.AddField(
            model_name='nodetrait',
            name='trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trait'),
        ),
        migrations.AddField(
            model_name='node',
            name='trait',
            field=models.ManyToManyField(through='core.NodeTrait', to='core.Trait'),
        ),
        migrations.AddField(
            model_name='expander',
            name='etype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EType'),
        ),
        migrations.AddField(
            model_name='expander',
            name='profile',
            field=models.ManyToManyField(through='core.ProfileExpander', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='profileexpander',
            name='expander',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Expander'),
            preserve_default=False,
        ),
    ]
