# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170126_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
