# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170126_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='title',
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
